# Generated by Django 5.2.7 on 2025-10-14 17:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loginhistory_usersession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'db_table': 'auth_email_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='auth_email__token_39109f_idx'), models.Index(fields=['user', '-created_at'], name='auth_email__user_id_1f0677_idx'), models.Index(fields=['email'], name='auth_email__email_1604c1_idx'), models.Index(fields=['expires_at'], name='auth_email__expires_e63de6_idx'), models.Index(fields=['is_used'], name='auth_email__is_used_44ae21_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reset_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reset_user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset',
                'verbose_name_plural': 'Password Resets',
                'db_table': 'auth_password_reset',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='auth_passwo_token_6ed6c4_idx'), models.Index(fields=['user', '-created_at'], name='auth_passwo_user_id_e1a2ae_idx'), models.Index(fields=['email'], name='auth_passwo_email_f4cbdf_idx'), models.Index(fields=['expires_at'], name='auth_passwo_expires_70a242_idx'), models.Index(fields=['is_used'], name='auth_passwo_is_used_9420ce_idx')],
            },
        ),
    ]
