# Generated by Django 5.2.7 on 2025-10-19 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('all_day', models.BooleanField(default=False)),
                ('location_name', models.CharField(max_length=300)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('venue_details', models.TextField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
                ('online_link', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('meetup', 'Meetup'), ('networking', 'Networking'), ('training', 'Training'), ('social', 'Social'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('business', 'Business'), ('educational', 'Educational'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite Only')], default='public', max_length=20)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('featured_image', models.URLField(blank=True)),
                ('banner_image', models.URLField(blank=True)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('organizer_name', models.CharField(blank=True, max_length=200)),
                ('organizer_description', models.TextField(blank=True)),
                ('agenda', models.JSONField(blank=True, default=list)),
                ('speakers', models.JSONField(blank=True, default=list)),
                ('sponsors', models.JSONField(blank=True, default=list)),
                ('requirements', models.TextField(blank=True)),
                ('what_to_bring', models.TextField(blank=True)),
                ('parking_info', models.TextField(blank=True)),
                ('accessibility_info', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('co_organizers', models.ManyToManyField(blank=True, related_name='co_organized_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'), models.Index(fields=['status'], name='events_even_status_5709b6_idx'), models.Index(fields=['category'], name='events_even_categor_aca11d_idx'), models.Index(fields=['privacy'], name='events_even_privacy_f67265_idx'), models.Index(fields=['is_featured'], name='events_even_is_feat_765082_idx')],
            },
        ),
    ]
